package com.intfic.game.enhanced;

import java.io.Serializable;

public enum EnhancedGameEditState implements Serializable {
   OPEN,
   ACTIONFORMAT,
   SAVE_FILENAME,
   START_MESSAGE,
   ROOM_NAME,
   ROOM_ITEMS,
   ITEM_SYNONYMS,
   ITEM_SYNONYMS_SPECIFIED,
   ACTION_ROOM,
   ACTION_TRIGGER,
   ACTION_TRIGGER_CLARIFY,
   ACTION_ARGS,
   ACTION_PRE,
   ACTION_POST,
   ACTION_MSG,
   EDIT_KNOWLEDGE,
   FILLERS,
   PARENTS_CHILD,
   PARENTS_PARENT,
   PARENTS_NEW_NAME,
   PARENTS_NEW_SLOTS,
   LOAD
}
