package com.intfic.game.basic;

public enum BasicGameEditState {
   OPEN,
   LOAD,
   ACTIONFORMAT,
   SAVE_FILENAME,
   START_MESSAGE,
   ROOM_NAME,
   ROOM_ITEMS,
   ITEM_SYNONYMS,
   ACTION_ROOM,
   ACTION_TRIGGER,
   ACTION_TRIGGER_CLARIFY,
   ACTION_ARGS,
   ACTION_PRE,
   ACTION_POST,
   ACTION_MSG,
   ITEM_SYNONYMS_SPECIFIED
}
