package com.basic;

public enum BasicGameEditState {
   OPEN,
   SAVE_FILENAME,
   ROOM_NAME,
   ROOM_ITEMS,
   ACTION_ROOM,
   ACTION_TRIGGER,
   ACTION_TRIGGER_CLARIFY,
   ACTION_ARGS,
   ACTION_PRE,
   ACTION_POST,
   ACTION_MSG
}
